config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'lists/index'
  root to: 'lists#index'
  get 'about', to: 'pages#about'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, :dependent => :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list) 
    else
      render :new
    end
  end
  
  def destroy 
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/new.html.erb
<div class="container form shadow-sm mt-5">
  <h1><%= "Add a movie to #{@list.name}" %></h1>
  <br>
  <%= simple_form_for [ @list, @bookmark ] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <div class='d-flex justify-content-between pt-4'>
      <p><%= link_to "Back", list_path(@list), class: "btn btn-secondary" %></p>
      <p><%= f.submit "Add movie", class: "btn btn-primary" %></p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <title><%= meta_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Roboto&display=swap" rel="stylesheet">
    <%# <meta name="viewport" content="width=device-width, initial-scale=1"> %>
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "lists/navbar" %>
    <div class='content'>
      <%= yield %>
    </div>
    <%= render "lists/footer" %>
  </body>
</html>

app/views/lists/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <div class="footer-links">
      <a href="https://github.com/jfaMan" target="_blank"><i class="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/in/allanszewczyk" target="_blank"><i class="fab fa-linkedin"></i></a>
      <a href="https://www.instagram.com/allanjs.photography/" target="_blank"><i class="fab fa-instagram"></i></a>
    </div>
    <p class="footer-break">|</p>
    <p>©2021 Allan Szewczyk. All Rights Reserved</p>
  </div>
</div>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to lists_path, class: "nav-link" do %>
    <div class="nav-logo">
      <i class="fas fa-film"></i>
      <div class="ml-1">LOUNGE</div>
    </div>
  <% end %>
  <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> %>
  <div class="navbar-right" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <%# <li class="nav-item active">
        <%= link_to "Home", lists_path, class: "nav-link" %>
      <%# </li> %>
      <li class="nav-item active">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>
<%# Line 11 - use 'collapse navbar-collapse' for dropdown or 'navbar-right' for button %>

app/views/lists/index.html.erb
<div>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1595769816263-9b910be24d5f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1958&q=80);">
    <div class="container">
      <h1><i class="fas fa-film"></i>LOUNGE</h1>
      <p>Find a movie to watch. Share your favourites.</p>
      <div class="mt-4 btn-div"><%= link_to "Create a new movie list", new_list_path, class: "btn btn-banner" %></div>
    </div>
  </div>
  <div class="cards container my-5">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_path("default.jpg") %>)">
        <%= link_to '', list_path(list), class: "card-category-link" %>
        <h3><%= list.name %></h3>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container form my-5">
  <h1>Create a new movie list</h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <div class='d-flex justify-content-between pt-4'>
      <p class='m-0'><%= link_to "Back to lists", lists_path, class: "btn btn-secondary" %></p>
      <p class='m-0'><%= f.submit "Create list", class: "btn btn-primary" %></p>
    </div>
  <% end %>
  <br>
</div>

app/views/lists/show.html.erb
<div>
  <div class="banner banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key, crop: :fill) : image_path("default.jpg", width: 400, height: 300, crop: :fill) %>)">
    <div class="container">
      <h1><%= "Best #{@list.name}" %></h1>
      <div class="mt-4"><%= link_to "Add a movie to this list", new_list_bookmark_path(@list), class: "btn btn-banner" %></div>
    </div>
  </div>
  <div class="bookmarks container mt-5">
    <% @list.bookmarks.each do |bookmark| %>
      <% url = "https://image.tmdb.org/t/p/w500#{bookmark.movie.poster_url}" %>
      <div class="bookmark rounded-0 shadow-sm position-relative">
        <%# <div class="bookmark-img"></div> %>
        <%= image_tag url, alt: "poster" %>
        <div class="bookmark-body">
          <h5 class="card-title font-weight-bold"><%= bookmark.movie.title %></h5>
          <p class="card-text"><%= bookmark.movie.overview %></p>
          <p>---------------------</p>
          <p><em><%= "'#{bookmark.comment}'" %></em></p>
          <p><strong><%= "Rating: #{bookmark.movie.rating}" %></strong></p>
          <div class="bookmark-body-icon">
            <%= link_to bookmark_path(bookmark), method: :delete, data: { confirm: 'Are you sure you want to remove this movie?' } do %>
              <i class="fas fa-minus-circle"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/about.html.erb
<div class='container mt-5 text-center'>
  <h1>About</h1>
  <img class='about-pic' src="https://avatars.githubusercontent.com/u/80769492?v=4" alt="Me">
  <div class="about-info">
    <p>This is my first project built at Le Wagon Tokyo. It's a simple web app that curates movies into watchlists using <a href="https://developers.themoviedb.org/3/getting-started/introduction" target="_blank"><em>The Movie Database (TMDB) API</em></a>.</p>
  </div>
</div>